/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as ApiSubscriptionCheckRouteImport } from './routes/api.subscription-check'
import { Route as ApiKeysRouteImport } from './routes/api.keys'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiBillingPortalRouteImport } from './routes/api.billing-portal'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiKeysRevokeRouteImport } from './routes/api.keys.revoke'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicV1CurrentRouteImport } from './routes/api.public.v1.current'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const ApiSubscriptionCheckRoute = ApiSubscriptionCheckRouteImport.update({
  id: '/subscription-check',
  path: '/subscription-check',
  getParentRoute: () => ApiRoute,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ApiRoute,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ApiRoute,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/billing-portal',
  path: '/billing-portal',
  getParentRoute: () => ApiRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKeysRevokeRoute = ApiKeysRevokeRouteImport.update({
  id: '/revoke',
  path: '/revoke',
  getParentRoute: () => ApiKeysRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CurrentRoute = ApiPublicV1CurrentRouteImport.update({
  id: '/public/v1/current',
  path: '/public/v1/current',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/premium': typeof PremiumRoute
  '/radar': typeof RadarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/news/$id': typeof NewsIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/keys/revoke': typeof ApiKeysRevokeRoute
  '/api/public/v1/current': typeof ApiPublicV1CurrentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/premium': typeof PremiumRoute
  '/radar': typeof RadarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/news/$id': typeof NewsIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/keys/revoke': typeof ApiKeysRevokeRoute
  '/api/public/v1/current': typeof ApiPublicV1CurrentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/premium': typeof PremiumRoute
  '/radar': typeof RadarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/news/$id': typeof NewsIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/keys/revoke': typeof ApiKeysRevokeRoute
  '/api/public/v1/current': typeof ApiPublicV1CurrentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/mcp'
    | '/news'
    | '/premium'
    | '/radar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/keys'
    | '/api/subscription-check'
    | '/news/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/keys/revoke'
    | '/api/public/v1/current'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/mcp'
    | '/news'
    | '/premium'
    | '/radar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/keys'
    | '/api/subscription-check'
    | '/news/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/keys/revoke'
    | '/api/public/v1/current'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/mcp'
    | '/news'
    | '/premium'
    | '/radar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/keys'
    | '/api/subscription-check'
    | '/news/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/keys/revoke'
    | '/api/public/v1/current'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  ApiRoute: typeof ApiRouteWithChildren
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  RadarRoute: typeof RadarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/subscription-check': {
      id: '/api/subscription-check'
      path: '/subscription-check'
      fullPath: '/api/subscription-check'
      preLoaderRoute: typeof ApiSubscriptionCheckRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/billing-portal': {
      id: '/api/billing-portal'
      path: '/billing-portal'
      fullPath: '/api/billing-portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof ApiRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/revoke': {
      id: '/api/keys/revoke'
      path: '/revoke'
      fullPath: '/api/keys/revoke'
      preLoaderRoute: typeof ApiKeysRevokeRouteImport
      parentRoute: typeof ApiKeysRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/current': {
      id: '/api/public/v1/current'
      path: '/public/v1/current'
      fullPath: '/api/public/v1/current'
      preLoaderRoute: typeof ApiPublicV1CurrentRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiKeysRouteChildren {
  ApiKeysRevokeRoute: typeof ApiKeysRevokeRoute
}

const ApiKeysRouteChildren: ApiKeysRouteChildren = {
  ApiKeysRevokeRoute: ApiKeysRevokeRoute,
}

const ApiKeysRouteWithChildren =
  ApiKeysRoute._addFileChildren(ApiKeysRouteChildren)

interface ApiRouteChildren {
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiKeysRoute: typeof ApiKeysRouteWithChildren
  ApiSubscriptionCheckRoute: typeof ApiSubscriptionCheckRoute
  ApiPublicV1CurrentRoute: typeof ApiPublicV1CurrentRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiKeysRoute: ApiKeysRouteWithChildren,
  ApiSubscriptionCheckRoute: ApiSubscriptionCheckRoute,
  ApiPublicV1CurrentRoute: ApiPublicV1CurrentRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  ApiRoute: ApiRouteWithChildren,
  McpRoute: McpRoute,
  NewsRoute: NewsRouteWithChildren,
  PremiumRoute: PremiumRoute,
  RadarRoute: RadarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
